export const VERSION_COLLECTION_PREFIX = "versions";
export const VERSION_DOCUMENT_PREFIX = `${VERSION_COLLECTION_PREFIX}/v1`;

export const USERS_COLLECTION_PREFIX = `${VERSION_DOCUMENT_PREFIX}/users`;
export const USERIDS_COLLECTION_PREFIX = `${VERSION_DOCUMENT_PREFIX}/userIds`;
